# Generated by Django 6.0.4 on 2026-04-18 19:42

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('uses_hormonal_contraception', models.BooleanField(default=False)),
                ('is_trying_to_conceive', models.BooleanField(default=False)),
                ('kalman_estimate', models.FloatField(default=28.0)),
                ('kalman_error', models.FloatField(default=10.0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('typical_start_day', models.PositiveSmallIntegerField()),
                ('typical_end_day', models.PositiveSmallIntegerField()),
                ('dominant_hormones', models.JSONField(blank=True, default=list)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('typical_end_day__gte', models.F('typical_start_day'))), name='typical_end_day_after_typical_start_day')],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('medical_term', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('positive', 'Positive'), ('neutral', 'Neutral')], max_length=10)),
                ('probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('description', models.TextField()),
                ('typical_start_day', models.PositiveSmallIntegerField()),
                ('typical_end_day', models.PositiveSmallIntegerField()),
                ('tips', models.JSONField(blank=True, default=list)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='cycle.phase')),
                ('related', models.ManyToManyField(blank=True, to='cycle.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow_level', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('none', 'None')], default='none', max_length=10)),
                ('spotting', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('fertile', models.BooleanField(blank=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cycle.phase')),
                ('symptoms', models.ManyToManyField(blank=True, to='cycle.symptom')),
            ],
        ),
        migrations.AddConstraint(
            model_name='symptom',
            constraint=models.CheckConstraint(condition=models.Q(('typical_end_day__gte', models.F('typical_start_day'))), name='symptom_typical_end_day_after_start_day'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
    ]
